baseurl = "https://spcubco.github.io/"
title = "Sports Programming Club"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 99
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
#copyright = "© 2019 — Some Author — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  #tag = "tags"
  #category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "notes"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
   [[menu.main]]
    url = "/training"
    name = "training"
    weight = 4
  [[menu.main]]
    url = "/calendar/"
    name = "calendar"
    weight = 3

  # Footer
  [[menu.footer]]
    name = "Meetings: Monday 18:00 - 20:00 @ FIP 124          "
    weight = 4
  [[menu.footer]]
    url = "https://discord.gg/hb3hGTb"
    name = "Discord"
    weight = 3
  [[menu.footer]]
    url = "https://www.facebook.com/spcubco/"
    name = "Facebook"
    weight = 1
  #[[menu.footer]]
    #url = "mailto:spc.ubco@gmail.com"
    #name = "Email"
    #weight = 2


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
